### ISSUE TITLE
ReadHex format

### ISSUE THREAD

**Issue by Rydgel** [ewestern/geos#1]
Hi,

I wanted to know the format read by GEOS.Serialize.readHex.
If I understand correcty, it's a .wbk file in base 16 (hexadecimal).
I've got issues reading my own file with that lib.

**Comment by Rydgel** [comment]
Forgot to put the stack trace

```
haskell-geo-exe(40254,0x7fff71ee7000) malloc: *** error for object 0x7ffcd9c055e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by ewestern** [comment]
Hi, sorry I missed this.
I'm not sure about that file type -- but if it was stored as a well-known binary it shouldn't be a problem.
This appears to be a bug in some of the FFI code, rather than an issue with file format --- will take a look.

**Comment by ewestern** [comment]
@Rydgel Actually, I'm not running into this issue. Perhaps you could upload the file you're working with?
